<section>
    <div class="container">
        <div class="row">

            <br/>

            <div class="breadcrumbs">
                <ol class="breadcrumb">
                    <li><a href="/admin/cabinet/cabinet">Cabinet</a></li>        
                    <li class="active">Manage orders</li>
                </ol>
            </div>

            <h4>Order list</h4>

            <br/>

            <table class="table">
                <tr>
                    <th>Order Id</th>
                    <th>Total Price</th>
                    <th>User Id</th>
                    <th>Created</th>
                    <th>User Name</th>
                    <th>User Email</th>
                    <th>User Phone</th>
                    <th>User Comment</th>
                </tr>
                <?php foreach ($orderList as $order): ?>
                    <tr>
                        <td><?php echo htmlentities($order['id'], ENT_QUOTES); ?></td>
                        <td><?php echo htmlentities($order['totalPrice'], ENT_QUOTES); ?></td>
                        <td><?php echo htmlentities($order['userId'], ENT_QUOTES); ?></td>
                        <td><?php echo htmlentities($order['created'], ENT_QUOTES); ?></td>
                        <td><?php echo htmlentities($order['userName'], ENT_QUOTES); ?></td>
                        <td><?php echo htmlentities($order['userEmail'], ENT_QUOTES); ?></td>
                        <td><?php echo htmlentities($order['userPhone'], ENT_QUOTES); ?></td>
                        <td><?php echo htmlentities($order['userComment'], ENT_QUOTES); ?></td>
                    </tr>
                <?php endforeach; ?>
            </table>

        </div>
    </div>
</section>