<section>
    <div class="container">
        <div class="row">
            <br/>

            <div class="breadcrumbs">
                <ol class="breadcrumb">
                    <li><a href="/cabinet/cabinet">Cabinet</a></li>
                    <li><a href="/products/index">Manage products</a></li>
                    <li class="active">New product</li>
                </ol>
            </div>


            <h4>Add new product</h4>

            <br/>
            <div class="col-lg-4">
                <div class="login-form">
                    <form action="#" method="post" enctype="multipart/form-data">

                        <p>Name</p>
                        <input type="text" name="name" placeholder="" value="">

                        <p>Sku</p>
                        <input type="text" name="sku" placeholder="" value="">
                        
                        <p>Qty</p>
                        <input type="text" name="qty" placeholder="" value="">

                        <p>Price, $</p>
                        <input type="text" name="price" placeholder="" value="">

                        <br/><br/>

                        <p>Description</p>
                        <textarea name="description"></textarea>

                        <p>Image</p>
                        <input type="file" name="image" placeholder="" value="">

                        <br/><br/>

                        <input type="submit" name="submit" class="btn btn-default" value="Save">

                        <br/><br/>

                    </form>
                </div>
            </div>

        </div>
    </div>
</section>