<section>
    <div class="container">
        <div class="row">
            <br/>

            <div class="breadcrumbs">
                <ol class="breadcrumb">
                    <li><a href="/admin/cabinet">Cabinet</a></li>
                    <li><a href="/products/index">Manage products</a></li>
                    <li class="active">Delete product</li>
                </ol>
            </div>
            
            <h4>Delete Product #<?php echo $id; ?></h4>


            <p>Are you sure you want to delete this product?</p>

            <form method="post">
                <input type="submit" name="submit" value="Delete" />
            </form>

        </div>
    </div>
</section>