<section>
    <div class="container">
        <div class="row">

            <br/>

            <div class="breadcrumbs">
                <ol class="breadcrumb">
                    <li><a href="/admin/cabinet/cabinet">Cabinet</a></li>
                    <li class="active">Manage product's</li>
                </ol>
            </div>

            <a href="/admin/products/create" class="btn btn-default back"><i class="fa fa-plus"></i> Add product </a>

            <h4>Products list</h4>

            <br/>

            <table class="table-bordered table-striped table">
                <tr>
                    <th>ID</th>
                    <th>Image</th>
                    <th>SKU</th>
                    <th>Name</th>
                    <th>Price</th>
                    <th></th>
                    <th></th>
                </tr>
                <?php foreach ($productList as $productItem): ?>
                    <tr>
                        <td><?php echo $productItem['id']; ?></td>
                        <td><img src="<?php echo $productItem['image']; ?>" width="50px" alt=""> </td>
                        <td><?php echo $productItem['sku']; ?></td>
                        <td><?php echo $productItem['name']; ?></td>
                        <td><?php echo $productItem['price']; ?></td>  
                        <td><a href="/admin/products/update/<?php echo $productItem['id']; ?>" title="Edit">Edit</td>
                        <td><a href="/admin/products/delete/<?php echo $productItem['id']; ?>" title="Delete">Delete</a></td>
                    </tr>
                <?php endforeach; ?>
            </table>

        </div>
    </div>
</section>

