<section>
    <div class="container">
        <div class="row">
            <br/>

            <div class="breadcrumbs">
                <ol class="breadcrumb">
                    <li><a href="/admin/cabinet">Cabinet</a></li>
                    <li><a href="/products/index">Manage products</a></li>
                    <li class="active">Edit product</li>
                </ol>
            </div>

            <h4>Edit product #<?php echo $id; ?></h4>

            <br/>

            <div class="col-lg-4">
                <div class="login-form">
                    <form action="#" method="post" enctype="multipart/form-data">

                        <p>Name</p>
                        <input type="text" name="name" placeholder="" value="<?php echo $product['name']; ?>">

                        <p>Sku</p>
                        <input type="text" name="sku" placeholder="" value="<?php echo $product['sku']; ?>">
                        
                        <p>Qty</p>
                        <input type="text" name="qty" placeholder="" value="<?php echo $product['qty']; ?>">

                        <p>Price, $</p>
                        <input type="text" name="price" placeholder="" value="<?php echo $product['price']; ?>">

                        <br/><br/>
                        
                        <p>Description</p>
                        <textarea name="description"><?php echo $product['description']; ?></textarea>

                        <p>Image</p>
                        <img src="<?php echo \Model\Product::getImage($product['id']); ?>" width="200" alt="" />
                        <input type="file" name="image" placeholder="" value="<?php echo $product['image']; ?>">

                        <br/><br/>
                        
                        <input type="submit" name="submit" class="btn btn-default" value="Save">
                        
                        <br/><br/>
                        
                    </form>
                </div>
            </div>

        </div>
    </div>
</section>