<section>
    <div class="container">
        <div class="row">

            <br/>

            <div class="breadcrumbs">
                <ol class="breadcrumb">
                    <li><a href="/admin/cabinet/cabinet">Cabinet</a></li>        
                    <li class="active">Manage category</li>
                </ol>
            </div>

            <a href="/admin/category/create" class="btn btn-default back"><i class="fa fa-plus"></i> Add category</a>

            <h4>Category list</h4>

            <br/>

            <table class="table-bordered table-striped table">
                <tr>
                    <th>Category ID</th>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Image</th>
                    <th></th>
                    <th></th>
                </tr>
                <?php foreach ($categoryList as $category): ?>
                    <tr>
                        <td><?php echo $category['id']; ?></td>
                        <td><?php echo $category['name']; ?></td>
                        <td><?php echo $category['description']; ?></td>
                        <td><img src="<?php echo $category['image']; ?>" width="50px" alt=""></td>  
                        <td><a href="/admin/category/update/<?php echo $category['id']; ?>" title="Edit">Edit</a></td>
                        <td><a href="/admin/category/delete/<?php echo $category['id']; ?>" title="Delete">Delete</a></td>
                    </tr>
                <?php endforeach; ?>
            </table>

        </div>
    </div>
</section>