<section>
    <div class="container">
        <div class="row">

            <br/>

            <div class="breadcrumbs">
                <ol class="breadcrumb">
                    <li><a href="/admin/cabinet/cabinet">Cabinet</a></li>        
                    <li class="active">Manage category</li>
                </ol>
            </div>

            <a href="/admin/categories/create" class="right">Add category</a>

            <h4>Category list</h4>

            <br/>

            <table class="table">
                <tr>
                    <th>Category ID</th>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Image</th>
                    <th></th>
                    <th></th>
                </tr>
                <?php foreach ($categoryList as $category): ?>
                    <tr>
                        <td><?php echo htmlentities($category['id'], ENT_QUOTES); ?></td>
                        <td><?php echo htmlentities($category['name'], ENT_QUOTES); ?></td>
                        <td><?php echo htmlentities($category['description'], ENT_QUOTES); ?></td>
                        <td><img src="<?php echo $category['image']; ?>" width="50px" alt=""></td>  
                        <td><a href="/admin/categories/update/<?php echo htmlentities($category['id'], ENT_QUOTES); ?>" title="Edit">Edit</a></td>
                        <td><a href="/admin/categories/delete/<?php echo htmlentities($category['id'], ENT_QUOTES); ?>" title="Delete">Delete</a></td>
                    </tr>
                <?php endforeach; ?>
            </table>

        </div>
    </div>
</section>