<section>
    <div class="container">
        <div class="row">

            <br/>

            <div class="breadcrumbs">
                <ol class="breadcrumb">
                    <li><a href="/admin/cabinet/cabinet">Cabinet</a></li>        
                    <li><a href="/admin/categories/index">Manage category</a></li>
                    <li class="active">Add category</li>
                </ol>
            </div>


            <h4>Add new category</h4>

            <br/>

            <div class="col-lg-4">
                <div class="login-form">
                    <form action="#" method="post" enctype="multipart/form-data">

                        <p>Name</p>
                        <input type="text" name="name" placeholder="" value="">

                        <p>Description</p>
                        <input type="text" name="description" placeholder="" value="">

                        <p>Image</p>
                        <input type="file" name="image" placeholder="" value="">

                        <br><br>

                        <input type="submit" name="submit" class="btn btn-default" value="Save">
                    </form>
                </div>
            </div>


        </div>
    </div>
</section>
