<section>
    <div class="container">
        <div class="row">

            <br/>

            <div class="breadcrumbs">
                <ol class="breadcrumb">
                    <li><a href="/admin/cabinet/cabinet">Cabinet</a></li>        
                    <li><a href="/admin/categories/index">Manage category</a></li>
                    <li class="active">Delete category</li>
                </ol>
            </div>


            <h4>Delete category #<?php echo $id; ?></h4>

            <br/>

            <p>Are you sure you want to delete this category?</p>

            <form method="post">
            <input type="submit" name="submit" value="Delete" />
            </form>

        </div>
    </div>
</section>
