<section>
    <div class="container">
        <div class="row">

            <br/>

            <div class="breadcrumbs">
                <ol class="breadcrumb">
                    <li><a href="/admin/cabinet/cabinet">Cabinet</a></li>        
                    <li><a href="/admin/category/index">Manage category</a></li>
                    <li class="active">Update category</li>
                </ol>
            </div>


            <h4>Update category "<?php echo htmlentities($category['name'], ENT_QUOTES); ?>"</h4>

            <br/>

            <div class="col-lg-4">
                <div class="login-form">
                    <form action="#" method="post" enctype="multipart/form-data">

                        <p>Name</p>
                        <input type="text" name="name" placeholder="" value="<?php echo htmlentities($category['name'], ENT_QUOTES); ?>">

                        <p>Description</p>
                        <input type="text" name="description" placeholder="" value="<?php echo htmlentities($category['description'], ENT_QUOTES); ?>">

                        <p>Products per category</p>
                        <select class = "multiple-block" multiple="multiple" name="productList[]">
                            <?php foreach ($productList as $productItem) : ?>
                                <option value="<?php echo htmlentities($productItem['id'], ENT_QUOTES); ?>"
                                <?php echo in_array($productItem['id'], $categoryProducts) ? 'selected' : '' ?>
                                        ><?php echo htmlentities($productItem['name'], ENT_QUOTES); ?></option>
                                    <?php endforeach; ?>
                        </select>

                        <p>Image</p>
                        <img src="<?php echo \Model\Admin\Category::getImage($category['id']); ?>" width="200" alt="" />
                        <input type="file" name="image" placeholder="" value="<?php echo $category['image']; ?>">

                        <br><br>

                        <input type="submit" name="submit" class="btn btn-default" value="Save">
                    </form>
                </div>
            </div>


        </div>
    </div>
</section>
