<div class="cart">
    <h2 class="title text-center">Cart</h2>
    <?php if ($productsInCart): ?>

        <p>Your products:</p>
        <table class="table-bordered table-striped table">
            <tr>
                <th>Image</th>
                <th>Name</th>
                <th>Price, $</th>
                <th>Qty</th>
                <th>Delete</th>
            </tr>
            <?php foreach ($productList as $product): ?>
                <tr>
                    <td><img src="<?php echo \Model\Admin\Products::getImage($product['id']); ?>" width="40px"></td>
                    <td>
                        <a href="/product/view/<?php echo $product['id']; ?>">
                            <?php echo $product['name']; ?>
                        </a>
                    </td>
                    <td><?php echo $product['price']; ?></td>
                    <td><?php echo $productsInCart[$product['id']]; ?></td> 
                    <td>
                        <a href="/cart/delete/<?php echo $product['id']; ?>">
                            <i class="delete">Delete</i>
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
            <tr>
                <td colspan="4">Total Price, $:</td>
                <td><?php echo $totalPrice; ?></td>
            </tr>

        </table>

        <a class="btn-checkout" href="/cart/checkout"><button>Go to checkout</button></a>
    <?php else: ?>
        <p>Cart is empty</p>
    <?php endif; ?>
    <a class="btn btn-default checkout" href="/"><i class="fa fa-shopping-cart">Back to the shopping</i></a>
</div>