<div class="features_items">
    <h2 class="title text-center">Checkout</h2>

    <p>Selected products: <?php echo $totalQuantity; ?>, for the amount: <?php echo $totalPrice; ?>, $</p><br/>

    <p>To place an order, fill out the form</p>

    <div class="login-form">
        <form action="" method="post">

            <p>Name</p>
            <input type="text" name="userName" placeholder="Name" />

            <p>Email</p>
            <input type="email" name="userEmail" placeholder="E-mail"/>

            <p>Phone</p>
            <input type="text" name="userPhone" placeholder="Phone" />

            <p>Comment to the order</p>
            <input type="text" name="userComment" placeholder="Comment"/>

            <br/>
            <br/>
            <input type="submit" name="submit" value="Submit" /> 
        </form>
    </div>
</div>

<a class="btn btn-default checkout" href="/"><i class="fa fa-shopping-cart">Back to the shopping</i></a>

</div>