<head>
    <title>Ism Local</title>
    <link rel="stylesheet" type="text/css" href="/css/style.css" />   
</head>
<body class="grey lighten-4">
    <nav class="white z-depth-0">
        <div class="container">
            <a href="/" class="brand-logo brand-text">Ism Local</a>
        </div>
        <form class="search" method="get" action= "/search/search">
            <input type="text" placeholder="Search.." name="search" required/>
            <button type="submit">Search</button>
        </form>
    </nav>