<head></head>
<body>
    <?php $categories = \System\App::getModel(\Model\Category::class)->getCategoriesList();
    ?>
    <div class="menu">
        <?php foreach ($categories as $categoryItem) : ?>

            <a class="menu-link" href="/category/view/<?php echo $categoryItem['id']; ?>">
                <?php echo htmlentities($categoryItem['name'], ENT_QUOTES); ?>
            </a>
        <?php endforeach; ?>
        <a class="admin-link" href="/admin/cabinet/login"> Login to admin cabinet</a>
    </div>
</body>
