<div class="product-details">
    <img src="<?php echo $product['image']; ?>" width="50px" alt=""> 
    <h1 class="Name"><?php echo htmlentities($product['name'], ENT_QUOTES); ?></a></h1>
    <p><?php echo htmlentities($product['id'], ENT_QUOTES); ?></p>
    <p><?php echo htmlentities($product['price'], ENT_QUOTES); ?></p>
    <p><?php echo htmlentities($product['description'], ENT_QUOTES); ?></p>
</div>