<div class="product-details">
    <img src="<?php echo $product['image']; ?>" width="50px" alt=""> 
    <h1 class="Name"><?php echo htmlentities($product['name'], ENT_QUOTES); ?></a></h1>
    <p><?php echo htmlentities($product['id'], ENT_QUOTES); ?></p>
    <p><?php echo htmlentities($product['price'], ENT_QUOTES); ?></p>
    <p><?php echo htmlentities($product['description'], ENT_QUOTES); ?></p>
    <form action="/cart/add/<?php echo $product['id']; ?>" method="post" ><label for="quantity">Quantity:</label>
        <input type="number" name="quantity" min="1" value="1">
        <button class="add-button" >Add to Cart</button></input></form>
</div>