<head></head>
<body>
    <div class = menu-link>

        
<?php foreach ($searchResult as $productItem) : ?>
            <div class="product">
                <text "Serach results:"/>
                <img src="<?php echo $productItem['Image']; ?>" width="50px" alt=""> 
                <h1 class="Name"><a href="#"><?php echo htmlentities($productItem['Name'], ENT_QUOTES); ?></a></h1>
                <p><?php echo htmlentities($productItem['Id'], ENT_QUOTES); ?></p>
                <p><?php echo htmlentities($productItem['Price'], ENT_QUOTES); ?></p>
                <p><?php echo htmlentities($productItem['Description'], ENT_QUOTES); ?></p>
            </div>   
<?php endforeach; ?>
    </div>

