<head></head>
<body>
    <div class = menu-link>

        <?php if (count($searchResult) > 0) {
            foreach ($searchResult as $productItem) :
                ?>
                <div class="product">
                    <text "Search results:"/>
                    <img src="<?php echo $productItem['image']; ?>" width="50px" alt=""> 
                    <h1 class="Name"><a href="/product/view/<?php echo $productItem['id']; ?>"><?php echo htmlentities($productItem['name'], ENT_QUOTES); ?></a></h1>
                    <p><?php echo htmlentities($productItem['id'], ENT_QUOTES); ?></p>
                    <p><?php echo htmlentities($productItem['price'], ENT_QUOTES); ?></p>
                    <p><?php echo htmlentities($productItem['description'], ENT_QUOTES); ?></p>
                </div>   
            <?php
            endforeach;
        } else {
            echo 'No results were found for your request.';
        }
        ?>
    </div>

