<section>
    <div class="container">
        <div class="row">

            <br/>

            <div class="breadcrumbs">
                <ol class="breadcrumb">
                    <li><a href="/admin/cabinet/cabinet">Cabinet</a></li>
                    <li class="active">Manage product's</li>
                </ol>
            </div>

            <a href="/admin/products/create" class="right"><i class="fa fa-plus"></i> Add product </a>

            <h4>Products list</h4>

            <br/>

            <table class="table">
                <tr>
                    <th>ID</th>
                    <th>Image</th>
                    <th>SKU</th>
                    <th>Name</th>
                    <th>Price</th>
                    <th></th>
                    <th></th>
                </tr>
                <?php foreach ($productList as $productItem): ?>
                    <tr>
                        <td><?php echo htmlentities($productItem['id'], ENT_QUOTES); ?></td>
                        <td><img src="<?php echo \Model\Admin\Products::getImage($productItem['id']); ?>" width="50px" alt=""> </td>
                        <td><?php echo htmlentities($productItem['sku'], ENT_QUOTES); ?></td>
                        <td><?php echo htmlentities($productItem['name'], ENT_QUOTES); ?></td>
                        <td><?php echo htmlentities($productItem['price'], ENT_QUOTES); ?></td>  
                        <td><a href="/admin/products/update/<?php echo htmlentities($productItem['id'], ENT_QUOTES); ?>" title="Edit">Edit</td>
                        <td><a href="/admin/products/delete/<?php echo htmlentities($productItem['id'], ENT_QUOTES); ?>" title="Delete">Delete</a></td>
                    </tr>
                <?php endforeach; ?>
            </table>

        </div>
    </div>
</section>

