
<?php include _DIR_ . 'Templates/Header.php'; ?>
<?php foreach ($productList as $productItem) : ?>
    <div class="product">
        <img src="<?php echo $productItem['Image']; ?>" width="50px" alt=""> 
        <h1 class="Name"><a href="#"><?php echo $productItem['Name']; ?></a></h1>
        <p><?php echo $productItem['Id']; ?></p>
        <p><?php echo $productItem['Price']; ?></p>
        <p><?php echo $productItem['Description']; ?></p>
    </div>   
    <?php endforeach;
include _DIR_ . 'Templates/Footer.php';
?>


</body>
</html>


